// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC898cvOary7LmdFQGd04QBPcgev7VXpR4',
    appId: '1:759378809444:web:b29d68e71a538dfdaf8571',
    messagingSenderId: '759378809444',
    projectId: 'bizlink-project',
    authDomain: 'bizlink-project.firebaseapp.com',
    storageBucket: 'bizlink-project.firebasestorage.app',
    measurementId: 'G-T95JT9GXC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDoWJFdgFcTk0dt877Be_AvSm9EiPUFtU',
    appId: '1:759378809444:android:02378e1b9e8fda17af8571',
    messagingSenderId: '759378809444',
    projectId: 'bizlink-project',
    storageBucket: 'bizlink-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwwDFGQ8t7DHJ5RcSfXjTJFzCNpNuzRpg',
    appId: '1:759378809444:ios:9e6ea0afbd6f2e0aaf8571',
    messagingSenderId: '759378809444',
    projectId: 'bizlink-project',
    storageBucket: 'bizlink-project.firebasestorage.app',
    iosClientId: '759378809444-amoouctti9h75aa56ojortbkvsfffp46.apps.googleusercontent.com',
    iosBundleId: 'com.richzach.bizlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwwDFGQ8t7DHJ5RcSfXjTJFzCNpNuzRpg',
    appId: '1:759378809444:ios:9e6ea0afbd6f2e0aaf8571',
    messagingSenderId: '759378809444',
    projectId: 'bizlink-project',
    storageBucket: 'bizlink-project.firebasestorage.app',
    iosBundleId: 'com.richzach.bizlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC898cvOary7LmdFQGd04QBPcgev7VXpR4',
    appId: '1:759378809444:web:d37680461fb75179af8571',
    messagingSenderId: '759378809444',
    projectId: 'bizlink-project',
    authDomain: 'bizlink-project.firebaseapp.com',
    storageBucket: 'bizlink-project.firebasestorage.app',
    measurementId: 'G-XD8V5TTLQK',
  );

}